### ISSUE TITLE
dxf open does not read x coordinate

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/tpl-docs#1]
I decided to test out the dxf open function in tplang.  I created a dxf file using inkscape and attempted to read it using tplang/open().  It appears to read the y coordinates correctly, but the x coordinate is always zero.

Here is a part of the input:
POLYLINE
  8
0
 62
     0
 66
     1
 10
0
 20
0
 30
0.0
 70
     1
 40
0.8
 41
0.8
  0
VERTEX
  8
0
 10
0.00553386
 20
0.059299
 30
0.0
 40
0.0111111
 41
0.0111111
  0
VERTEX
  8
0
 10
0.00553386
 20
11.9435
 30
0.0
 40
0.0111111
 41
0.0111111
  0
VERTEX
  8
0
 10
7.83914
 20
11.9256
 30
0.0
 40
0.0111111
 41
0.0111111
  0
VERTEX
  8
0
 10
7.83914
 20
0.00575086
 30
0.0
 40
0.0111111
 41
0.0111111
  0
VERTEX
  8
0
 10
0.00553386
 20
0.059299
 30
0.0
 40
0.0111111
 41
0.0111111
  0
SEQEND
 8
0

And here is the associated output:

{"vertices":[{"x":0,"y":0.059299,"z":0,"type":0},{"x":0,"y":11.9435,"z":0,"type":0},{"x":0,"y":11.9256,"z":0,"type":0},{"x":0,"y":0.00575086,"z":0,"type":0},{"x":0,"y":0.059299,"z":0,"type":0}],"type":3}

**Comment by jcoffland** [comment]
Can you attach the full .dxf file?  I haven't tried it with Inkscape output.  It has worked for me in the past with LibreCAD DXF files.  There may be differences.

**Comment by jcoffland** [comment]
Scratch that, I figured out what was wrong and checked in a fix.  Bugs like this should not be filed in tpl-docs.  They should be filed in CauldronDevelopment/OpenSCAM.
